# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "Aula_1" ]
  pull_request:
    branches: [ "Aula_1" ]

jobs:

#Subindo os Banco de Dados e testando aplicação

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build DataBase
      run: docker-compose build

    - name: create DataBase
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go

#Criando o Build da aplicação      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Build
      run: go build -v main.go
